### ISSUE TITLE
C++ Support

### ISSUE THREAD

**Issue by youngie** [khoih-prog/ESP32TimerInterrupt#7]
Due the callback function definition this doesn't seem to support C++ method callbacks. This makes it necessary for the user to create a free function, not part of the C++ class in order to incorporate this in to C++ classes effectively unless there is some kind of Lambda expression work-around?

**Comment by khoih-prog** [comment]
@youngie 

Thanks for your interest in the library.

In general to save us some time to investigate the issue, you have to include in details

- the test code to enable issue duplication
- use case, if necessary

so that other people can duplicate the issue and solve it.

In general, the function pointers can be used as Callbacks in C and/or C++.

I think as you're good and using C++, it's an easy job to use them directly or simply convert, using whatever way you'd like, and use in your code.

I'm closing the issue now. Post if you have new thing to add.
